stages:
  preprocess:
    cmd: python src/data_prep.py
    deps:
      - src/data_prep.py
      - data/raw/train.csv
    outs:
      - data/processed/train_processed.csv

  train:
    cmd: python src/train.py
    deps:
      - src/train.py
      - data/processed/train_processed.csv
    outs:
      - models/model.pkl

  evaluate:
    cmd: python src/evaluate.py
    deps:
      - src/evaluate.py
      - models/model.pkl
    outs:
      - reports/metrics.json
      - reports/confusion_matrix.png
